name: Build and Publish image to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  publish-runner-image:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build linux/arm64 Docker Image
        run: |
          docker build -t thatssatyadocker/github-runner:latest .
      - name: Push to Docker Hub
        run: |
          docker login -u thatssatyadocker -p ${{ secrets.DOCKER_HUB_SECRET }}
          docker push thatssatyadocker/github-runner:latest