name: Build and Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish-runner-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build . -t thatssatyadocker/github-runner:latest
      - name: Push to Docker Hub
        run: |
          docker login -u thatssatyadocker -p ${{ secrets.DOCKER_HUB_SECRET }}
          docker push thatssatyadocker/github-runner:latest