name: Build and Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build . -t thatssatyadocker/github-runner:latest
      - name: push image to docker hub
        run: |
          docker login -u thatssatyadocker -p ${{ secrets.DOCKER_HUB_SECRET }}
          docker push thatssatyadocker/github-runner:latest